//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TodoApp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddItemButton {
            get {
                return ResourceManager.GetString("AddItemButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Item.
        /// </summary>
        public static string AddItemHeading {
            get {
                return ResourceManager.GetString("AddItemHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thing to do.
        /// </summary>
        public static string AddItemLabel {
            get {
                return ResourceManager.GetString("AddItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy eggs 🥚.
        /// </summary>
        public static string AddItemPlaceholder {
            get {
                return ResourceManager.GetString("AddItemPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TodoApp.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string CompleteItemButton {
            get {
                return ResourceManager.GetString("CompleteItemButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark this item as done..
        /// </summary>
        public static string CompleteItemLabel {
            get {
                return ResourceManager.GetString("CompleteItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © {0:yyyy} - {1}.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteItemButton {
            get {
                return ResourceManager.GetString("DeleteItemButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this item from the list..
        /// </summary>
        public static string DeleteItemLabel {
            get {
                return ResourceManager.GetString("DeleteItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        public static string ErrorHeading {
            get {
                return ResourceManager.GetString("ErrorHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request ID:.
        /// </summary>
        public static string ErrorRequestId {
            get {
                return ResourceManager.GetString("ErrorRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string ErrorSubheading {
            get {
                return ResourceManager.GetString("ErrorSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ListColumn1 {
            get {
                return ResourceManager.GetString("ListColumn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        public static string ListColumn2 {
            get {
                return ResourceManager.GetString("ListColumn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relax - You&apos;ve done everything! 🌈.
        /// </summary>
        public static string ListCompleted {
            get {
                return ResourceManager.GetString("ListCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Things To Do.
        /// </summary>
        public static string ListHeading {
            get {
                return ResourceManager.GetString("ListHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My List.
        /// </summary>
        public static string ListSubheading {
            get {
                return ResourceManager.GetString("ListSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My List.
        /// </summary>
        public static string ListTitle {
            get {
                return ResourceManager.GetString("ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My List.
        /// </summary>
        public static string NavListText {
            get {
                return ResourceManager.GetString("NavListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My TODO List.
        /// </summary>
        public static string NavListTitle {
            get {
                return ResourceManager.GetString("NavListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string PageTitleFormat {
            get {
                return ResourceManager.GetString("PageTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Language.
        /// </summary>
        public static string SwitchLanguage {
            get {
                return ResourceManager.GetString("SwitchLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle navigation.
        /// </summary>
        public static string ToggleNavigationAriaLabel {
            get {
                return ResourceManager.GetString("ToggleNavigationAriaLabel", resourceCulture);
            }
        }
    }
}
